name: 'member-dev branch check & auto-pr'
on:
  push:
    branches:
      - member-dev

jobs:
  build-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: member-dev
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Run test
        run: 'chmod +x ./gradlew && ./gradlew test'
  auto-pr:
    name: Auto doing pull request
    needs: build-check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: member-dev
      - name: Do Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          branch: wait-pr
          draft: true
